[tool.poetry]
name = "qosst-sim"
version = "0.10.0"
description = "Simulation module of QOSST."
authors = [
    "Mayeul Chavanne <mayeul.chavanne@ensta-paris.fr>",
    "Yoann Piétri <Yoann.Pietri@lip6.fr>",
]
packages = [{ include = "qosst_sim" }, { include = "qosst_sim/py.typed" }]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/qosst"
repository = "https://github.com/qosst/qosst-sim"
documentation = "https://qosst-sim.readthedocs.io/"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Security :: Cryptography",
]

[tool.poetry.dependencies]
python = ">=3.9, <3.14"
#qosst-core = "^0.10.0"
qosst-core = { git = "https://github.com/qosst/qosst-core", branch = "dev" }
#qosst-skr = "^0.10.0"
qosst-skr = { git = "https://github.com/qosst/qosst-skr", branch = "dev" }


[tool.poetry.group.dev.dependencies]
Sphinx = [
    { version = "^5.0.0", python = ">=3.9, <3.10" },
    { version = "^8.1.0", python = ">=3.10, <3.14" },
]
sphinx-rtd-theme = [
    { version = "^1.0.0", python = ">=3.9, <3.10" },
    { version = "^3.0.0", python = ">=3.10, <3.14" },
]
docstr-coverage = "^2.2.0"
myst-parser = [
    { version = "^1.0.0", python = ">=3.9, <3.10" },
    { version = "^4.0.0", python = ">=3.10, <3.14" },
]
black = "^23.3.0"
pylint = "^3.3.0"
matplotlib = [
    { version = "^3.5.1", python = ">=3.7, <3.11" },
    { version = "^3.7.1", python = ">=3.11, <3.12" },
]
sphinx-prompt = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
